// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://bqmadlgevzscpwafuswg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxbWFkbGdldnpzY3B3YWZ1c3dnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA2MTM3MzcsImV4cCI6MjA5NjE4OTczN30.7evRnAIWYqlI0rLe1AHYiW_oYv9qLErrZsYrndS4NA0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);